# Generated by Django 5.2.7 on 2025-11-02 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout', '0006_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('total_weights', models.PositiveIntegerField(blank=True, null=True)),
                ('total_duration', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='workout.workoutschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ReportExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights_lifted', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reps_completed', models.PositiveIntegerField(default=0)),
                ('sets_completed', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutexercises')),
            ],
        ),
    ]
