# Generated by Django 5.2.7 on 2025-11-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='workout_id',
            new_name='workout',
        ),
        migrations.AlterField(
            model_name='reportexercise',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exercise', to='reports.report'),
        ),
    ]
