# Generated by Django 5.2.7 on 2025-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('cardio', 'cardio'), ('strength', 'strength'), ('flexibility', 'flexibility')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('muscle_group', models.CharField(blank=True, choices=[('chest', 'chest'), ('back', 'back'), ('legs', 'legs'), ('arms', 'arms'), ('core', 'core'), ('all', 'all')], max_length=20, null=True)),
            ],
        ),
    ]
