# Generated by Django 5.2.7 on 2025-11-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('workout', '0004_alter_report_workout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercises',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.exercise'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
