# Generated by Django 5.2.7 on 2025-11-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_workoutexercises_exercise_delete_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
