# Generated by Django 5.2.7 on 2025-10-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(blank=True, choices=[('chest', 'chest'), ('back', 'back'), ('legs', 'legs'), ('arms', 'arms'), ('core', 'core'), ('all', 'all')], max_length=20, null=True),
        ),
    ]
