# Generated by Django 5.2.7 on 2025-10-30 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workoutexercises_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='workout.workoutschedule'),
        ),
    ]
